name: build
on: push

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        defaults:
            run:
                shell: ${{ matrix.os == 'windows-latest' && 'cmd' || 'bash' }}

        env:
            CI: true

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: bahmutov/npm-install@v1

            - name: check and build
              run: |
                  npm run check
                  npm run build
