name: release
on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: bahmutov/npm-install@v1

            - name: build
              run: npm run build

            - name: publish npm stable
              uses: epeli/npm-release@v1
              with:
                  type: stable
                  token: ${{ secrets.NPM_TOKEN }}

            # https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages
            # Setup .npmrc file to publish to GitHub Packages (can replace the other setup-node action when we no longer publish to npm)
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 16
            # Publish to GitHub Packages
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
